name: build
on: [push]
jobs:
  build-scope:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      # - run: apt-get update && apt-get install -y git
      - run: ./install_build_tools.sh
      - run: make deps
      - run: docker-compose version; cat /etc/lsb-release
      - run: make all
      - run: make test

      - uses: docker/login-action@v1
        with:
          username: jbieron
          password: ${{ secrets.DH_PASS }}
      - run: test/run_integ.sh

      - env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          CF_DISTRIBUTION_ID: ${{ secrets.CF_DISTRIBUTION_ID }}
        run: ./deploy.sh
      - if: startsWith(github.ref, 'refs/tags/v')
        env:
          SCOPECI_TOKEN: ${{ secrets.SCOPECI_TOKEN }}
        run: ./docker/build.sh
