name: build
on: [push]
jobs:
  build-scope:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      # - run: apt-get update && apt-get install -y git
      - run: ./install_build_tools.sh
      - run: make deps
      - run: make all
      - run: make test
      - run: cd test/testContainers && docker-compose up cribl detect_proto elastic gogen interposed_func kafka nginx splunk tls
      - env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          CF_DISTRIBUTION_ID: ${{ secrets.CF_DISTRIBUTION_ID }}
        run: ./deploy.sh
      - if: startsWith(github.ref, 'refs/tags/v')
        env:
          SCOPECI_TOKEN: ${{ secrets.SCOPECI_TOKEN }}
        run: ./docker/build.sh
